baseURL = "http://rac-tv.com/"
languageCode = "fr-ch"
title = "Rac-TV"
theme = "ananke"

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  AuthorName = "Yvan Racordon"
  favicon = ""
  description = "Rac-TV"
  background_color_class = "bg-black"
  featured_image = "/images/header.jpg"
  recent_posts_number = 2
  disableReadingTime = false
