baseURL = "https://rac-tv.com/"
languageCode = "fr-ch"
title = "Rac-TV"
theme = "ananke"

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = "UA-147135494-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  AuthorName = "Yvan Racordon"
  favicon = ""
  description = "Rac-TV"
  background_color_class = "bg-gray"
  featured_image = "/images/header.jpg"
  recent_posts_number = 20
  disableReadingTime = false
